### ISSUE TITLE
Cork version

### ISSUE THREAD

**Issue by oliver-moran** [future-analytics/reusingdublin#113]
I'm just hacking around at the minute but what would be the preferred way of handling different cities? Should just do a fork for Cork? Or would something more elegant be preferred?

A potential risk of being elegant is that it may end up being more hack-ish than elegant over the longer term (assuming the Cork and Dublin communities will want slightly different things).

A risk of doing a fork is that the code base will start to stray unnecessarily.

Just some thoughts. Any comments?

**Comment by future-analytics** [comment]
No problem, we would prefer the fork method. 

A strong measure of stray from the initial codebase would also signify more innovation towards solving the problems - ie open data of unused properties. In a situation where there would be many competing forks of a project then it would be up to the demand to decide which to stick with. As far as recognition for work done on the project, using the fork method keeps the history intact and traceable.

Once the license and history are kept then it is ok to do as you please, fork, download etc. Advantage of a fork though, is that we can then all see the improvements and innovations that others have done and then work on top of these through collaboration - daithi

**Comment by oliver-moran** [comment]
Sounds like the right approach.
